### ISSUE TITLE
.env のファイルないと動かないですね

### ISSUE THREAD

**Issue by o-ga09** [memememomo/clean-serverless-book-sample-v3#1]
１章のサンプルを動作させるために
プロジェクトルートに`.env`を配置しないと動かない

```
DYNAMO_TABLE_NAME=users
DYNAMO_PK_NAME=user_name
DYNAMO_SK_NAME=email
```

**Comment by memememomo** [comment]
@o-ga09 
すみません、このリポジトリへコードを移動する際に漏れてしまっていたみたいです 🙇‍♂️ 
修正しました、ご報告ありがとうございます！

**Comment by o-ga09** [comment]
@memememomo 
ご対応ありがとうございました！
